### ISSUE TITLE
Home screen/Entry list

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#1]
## 💰 Feature

User can view a list of their entries

## 🗒️ Notes

This will require me to have the client make a GET request to the server. 
The server queries the database and returns all the entries that the user created. (Work on backend first)
Client loops through what was sent from the server, making a list item react element and append it to an unordered list react element.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102941468-a544c580-4467-11eb-9209-70df590c8c5b.png)

## ✅ Tasks
- [x] Create a route in `server/index.js` to handle GET requests at `/api/entries`.
- [x] Write a sql statement that returns all entries tied to the user.
- [x] Query the database and send the result to the result to the client.
- [x] Catch any errors that might occur.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen shown in the wireframe.
- [x] Have the component fetch data from the server and display it as a list
