### ISSUE TITLE
User can export graph to pdf file

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#10]
## 💰 Feature

User can export graph to pdf file

## 🗒️ Notes

This will require me to have the client send a GET request.
Create an empty pdf and insert the bar graph image into it.
Output it to a folder.

## ✅ Tasks
- [x] Install the jspdf library with `npm install jspdf`
- [x] Create a pdf object 
  - [x] Add the graph
  - [x] Configure the graph
- [x] Create a button
  - [x] Generate a pdf for `onClick`
- [x] Fix image `width` and `height` in the pdf generated
