### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#11]
## 💰 Feature

User can sign in

## 🗒️ Notes

This will require me to use me to have the client make a POST request to the server.
Server checks if the information received is valid.
Hash the password.
The server queries the database and to check if their is a matching entry.
Create a token for the user if their is a match.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102949422-1cd11f80-447d-11eb-8464-151b59b1d60e.png)

## ✅ Tasks
- [x] Create a `POST` route `/api/user-sign-in/` in the server
- [x] Validate both `username` and `password` has value
- [x] Write an sql statement that returns `userId` and `hashedPassword` of the matching entry with the same `username`
- [x] Query the database and compare the hashedPasswords with `argon2` 
  - [x] Create a `jwt token` if the hashedPasswords matches
  - [x] Return the token
- [x] Test the sign in route with HTTPie
- [x] Create a component that renders the displayed view in the wireframe
  - [x] Create a `form`
  - [x] Add 2 input fields for `username` and `password` to the form
    - [x] Add an `onChange` prop that calls the `handleChange` method to both the username and password
      - [x] `handleChange` updates the `username` and `password` property in the state
  - [x] Add a `button` the form
  - [x] The form sends a `POST` request `onSubmit`
- [x] Add `contextType` for the user information
- [x] Include the context where it is necessary
- [x] Add the provider in the `App.jsx` file
  - [x] Include the user information, sign in method and sign out method into the context that was received from the server
- [x] Retrieve token from the `localStorage` in `componentDidMount` and decode it
  - [x] Add a guard in the render method to prevent the page from loading before token is retrieved
- [x] Add authentication middleware in the server
- [x] Save the signed token in the `state`
- [x] Pass the signed token to the other pages using the context
  - [x] Add the token to the header in each request
