### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#13]
## 💰 Feature

User can view a list of total monthly expenses

## 🗒️ Notes

This will require me to remove the token from the user.
Switch view to login page

## ✅ Tasks
- [x] Create a `handleSignOut` method in `app.jsx` file
  - [x] Remove the token from localStorage
  - [x] Set the value of `user` and `signedToken` to `null` in state
  - [x] Change the window hash value to empty string
- [x] Bind the `this` in constructor
- [x] Add the method to the context object
- [x] Create a sign out button in the menu
  - [x] Calls the sign out method from the context for `onClick`
  - [x] Change display to the sign in page
