### ISSUE TITLE
User can view an entry

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#2]
## 💰 Feature

User can view and edit an entry

## 🗒️ Notes

This will require me to have the view button render a page that displays the selected entry information. Send a GET request to the server. Server sends back a single entry after querying the database.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102944993-54d26580-4471-11eb-8a19-81ba14745709.png)

## ✅ Tasks
- [x] Create a route to the `server/index.js` to handle GET requests at `api/entry/entryId`.
- [x] Create data validations.
- [x] Write a sql statement that returns a single entry.
- [x] Catch any error that might occur.
- [x] Test the route with HTTPie.
- [x] Add hash routing
- [x] Define a component that renders the screen as shown in the wireframe.
- [x] Have the client send a GET request.
- [x] Server returns 1 entry instead of an array
- [x] Make the table full width of the screen
