### ISSUE TITLE
User can use a demo account

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#25]
## 💰 Feature

User can use a demo account

## ✅ Tasks
- [x] Add some demo users to the `database/data.sql` along with some example data
- [x] Add a button to the login screen
  - [x] `onClick` it will
    - [x] Set the initial username and password state in the login form to the values used by one of the demo users.
    - [x] Disable the username and password inputs so that nothing else can be typed into them.
