### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#27]
## 🗒️ Notes
1. The layout is not broken on or between any of these. Test by expanding the browser viewport from narrow to wide with your mouse.
2. The app looks appropriate for each screen type with common navigation. If you cannot find an example, real-world application on mobile, tablet, or desktop that uses the same style of navigation, then your navigation is inappropriate.
3. Fonts and buttons are larger when needed. Again compare your app to other real applications.
4. Use breakpoints (media queries) for each screen size

## ✅ Tasks
- [x] Add a container for the tables in desktop view
  - [x] Set `max-width` of display containers to `600px`
- [x] Add `max-width` to the `body` CSS selector and set it to `500px`
- [x] Add media query
  - [x] Change the `min-width` in the `body` CSS selector to `auto`
