### ISSUE TITLE
User can edit an entry

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#3]
## 💰 Feature

User can edit an entry

## 🗒️ Notes

This will require me to have the client send a POST request to the server. The server updates the database and returns the updated entry

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102946307-19d23100-4475-11eb-9660-6198e203abf8.png)

## ✅ Tasks
- [x] Write an sql statement that updates an entry with matching entryId
- [x] Validate the information sent from client
- [x] Query and update the database and send the result back to the client
- [x] Catch any error that might occur
- [x] Test the api route
- [x] Create an edit button on the single entry display page
- [x] Edit button redirects user to a new view
- [x] Create a form with the necessary inputs
- [x] write an sql statement that returns the category table
- [x] Query the database and return the result
- [x] Catch any error that might occur
- [x] Test the route
- [x] Add a componentDidMount that sends 2 get requests
     - [x]  Get the entry with matching entryId 
     - [x] Get all entries in the category table
- [x] Populate the form with the information from the server response 
     - [x] Add onChange props and bind the methods
- [x] Create a save button that sends a put request to the server with the edited information
- [x] Save button redirects the user back to the single entry display page
- [x] Add CSS
- [x] Remove For loop that finds categoryId by comparing category name and add categoryId column to the return in the server
- [x] Change the anchor tag back to a button and change `window.location.hash` in a handleSubmit function
- [x] Change `handleClick` to `handleSubmit`
- [x] Reduce the number of `handleChange` functions by including a `name` prop and using bracket notation
- [x] Change the comparison for the date length to be `=== 3`
- [x] Use more bootstrap css to remove more custom css
- [x] Change `window.location.hash` after fetch succeeds
