### ISSUE TITLE
User can add an entry

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#4]
## 💰 Feature

User can add an entry

## 🗒️ Notes

This will require me to have the client send a POST request to the server. Server adds the entry to the database after validating the information received.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102946470-9fee7780-4475-11eb-934d-3f2157b8b7b3.png)

## ✅ Tasks
- [x] Create a post route to add an entry
- [x] Write an SQL statement that inserts a new row into the entry table
- [x] Validate the information sent from the client
- [x] Create and insert the new row to the entry table
- [x] Catch any errors that might occur
- [x] Test the route
- [x] Add a button on home screen that redirects the user to the add entry page
- [x] Create a form page with the necessary inputs
     - [x] Use `select` tag for category input
     - [x] Use type `date` for the date input
     - [x] Use type `text` for the amount input
     - [x] Use `textarea` tag for the description
- [x] Use `componentDidMount` and send a `GET` request to the server for all rows in the category table 
- [x] Create an `Add Entry` button
     - [x] Sends a post request
- [x] Add CSS
- [x] Reset the property in `this.state` instead of querying the DOM for the form to reset the input
- [x] Change the view buttons to anchor tags in the home screen
- [x] Change the Edit button to an anchor tag in the single entry display page
