### ISSUE TITLE
User can navigate to other views with the menu

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#5]
## 💰 Feature

User can edit an entry

## 🗒️ Notes

This will require me to create a component that reveals the menu on click. Menu contains links to other views. Menu closes when a link or the area other than the menu is clicked

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102946832-a5988d00-4476-11eb-9144-e117a6171c6a.png)

## ✅ Tasks
- [x] Add a menu icon to the header
  - [x] menu appears on the side of the screen `onClick`, rest of the screen is dimmed
  - [x] Add links to the menu
    - [x] home screen
  - [x] Close menu after clicking a link or outside the menu 
  - [x] Change the unit for the menu width to `px`
  - [x] Remove the css that positions the link text in the center
