### ISSUE TITLE
User can view a list of total monthly expenses

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#6]
## 💰 Feature

User can view a list of total monthly expenses

## 🗒️ Notes

This will require me to use me to have the client make a GET request to the server.
Need to group the entries by month and year.
The server queries the database and returns the result.
Client loops through what was sent from the server, making a list item react element and append it to an unordered list react element.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102947199-9fef7700-4477-11eb-8abe-153fa423e5cb.png)

## ✅ Tasks
- [x] Create a route to handle `GET` requests at `/api/monthly-expense`
- [x] Write a sql statement that returns the total amount spent each month
- [x] Query the database and return the result back to the client
- [x] Catch any error that might occur
- [x] Test the route with HTTPie
- [x] Define a component that renders the screen shown in the wire frame
  - [x] Display the information using a `table`
- [x] Client sends a `GET` request to the `/api/monthly-expense` route
- [x] Remove the links to view the individual months
- [x] Change the CSS for the tables
- [x] Remove subquery in sql statement
