### ISSUE TITLE
User can view their monthly expenses by category

### ISSUE THREAD

**Issue by allen-huang9** [allen-huang9/final-project#7]
## 💰 Feature

User can view their monthly expenses by category

## 🗒️ Notes

This will require me to have the add button open a modal when clicked.
The server queries the database
Loop through result from the query return, create a variable for each category to hold the total sum.
Return the generated graph image url after the loop is.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/8008839/102947852-2d7f9680-4479-11eb-8cb2-7e5ce0701021.png)

## ✅ Tasks
- [x] Create a `GET` route for `/api/monthly-expense-graph/userId/month/year`
- [x] Write a sql statement that retrieves all the entries with the correct month and year
- [x] Verify the information received from the Client
- [x] Query the database and send the results back to client
- [x] Create a view button
  - [x] Has an `onClick`
    - [x] Sends a `GET` request to the server route `/api/monthly-expense-graph/userId/month/year`
    - [x] Use the information received from the server to create a `bar` graph
    - [x] opens a modal
- [x] Create a modal
  - [x] Has a button that closes it
  - [x] Shows the `Month` and `year`
  - [x] Displays the generated graph
  - [x] Shows the `total sum` spent during that month
  - [x] Format the data used for the bar graph in the server
